### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Minc3** [cabernetwork/provider_video_daddylive#13] opened 2024-05-02 09:06 UTC
Is this working for anyone?
It works fine on the website but not though this.

**Comment by rocky4546** [comment] 2024-05-02 16:18
I see they have changed the encryption key retrieval.  Will take a look and see what needs to change.

**Comment by jerrymolenaar** [comment] 2024-05-03 22:29
> I see they have changed the encryption key retrieval. Will take a look and see what needs to change.

Thanks for looking at this.   Same issue!

**Comment by purplescorpion1** [comment] 2024-05-04 12:28
hopefully it can be fixed

**Comment by benjaminfrombe** [comment] 2024-05-23 12:45
@rocky4546 Do you think you will be able to fix this ? My set-up was kind of based on this  :) If not, I'll have to look for other solutions (like kodi) ... Thanks for keeping us updated !

**Comment by rocky4546** [comment] 2024-05-23 18:11
I had a few moments to take a look.  FYI, anyone can make a PR and change the code to have it work.  The issue is the referrer is now only the site and not the complete URL.  Will make a few changes and see if that fixes it.

**Comment by rocky4546** [comment] 2024-05-23 19:13
release 21 is out.  checked on test server and it works.  migrating to production server and testing there.  Make sure to run a channel update (which should happen if you have had it down and re-enabled it)

**Comment by benjaminfrombe** [comment] 2024-05-23 19:46
Thanks, it works ! 
I did have to go to data management and perform a reset channel data, 
the scheduled task alone wasn't enough.

**Comment by rocky4546** [comment] 2024-05-23 20:29
Only other issue I found was that the channels in Kodi were not in the correct order and the channel numbers were off.  Found out it was caused by TVH.  I had to delete all DL muxes, services and channels and then do a forced scan before the channel numbers came in correctly.

**Comment by Nostradamus1973** [comment] 2024-05-23 20:46
> release 21 is out. checked on test server and it works. migrating to production server and testing there. Make sure to run a channel update (which should happen if you have had it down and re-enabled it)

Working great for me, thx @rocky4546 for fixing this.
Have a great night everyone.

**Comment by jerrymolenaar** [comment] 2024-05-23 23:07
Works for me as well, thanks for the solution!   I also had to go to data management and reset the channel data before it worked for me.

**Comment by Lowclock** [comment] 2024-05-25 20:04
It was good after you fixed it, but looks like it's already broken again. I can watch fine on their website, and refresh the channel list, but the plugin fails to retrieve any channels.

[daddylive.log](https://github.com/cabernetwork/provider_video_daddylive/files/15444852/daddylive.log)

**Comment by rocky4546** [comment] 2024-05-25 22:40
I have no info on what is causing Cabernet to terminate the stream.  Will need to take a look when I have a chance.

**Comment by purplescorpion1** [comment] 2024-05-25 23:14
> I have no info on what is causing Cabernet to terminate the stream. Will need to take a look when I have a chance.

It maybe cloudflare blocking the connection

**Comment by vortex91** [comment] 2024-05-26 00:56
Kodi addon also down

**Comment by subby2006** [comment] 2024-05-26 03:04
> I have no info on what is causing Cabernet to terminate the stream. Will need to take a look when I have a chance.

Daddylive changed domains again, it's now dlhd.so

**Comment by drysun2008** [comment] 2024-05-26 19:29
looks like the url needs to be updated as well as the search_m3u8 but not sure how to use github to submit changes.

I found I had to make 2 edits.
channels.py line 40, change the regex (found in kodi addon)

**Comment by Lowclock** [comment] 2024-05-26 20:03
> ` self.search_m3u8 = re.compile(b'(?:source|src|file):\s*[\'"]([^\'"]+)')`
This fixed it for me.

> `daddylive_base = 'gfpMXf5BjIUoyx3oj8lQjG=='`
This is what my translations.py already had.

**Comment by benjaminfrombe** [comment] 2024-05-26 20:15
created PR #14

**Comment by drysun2008** [comment] 2024-05-26 21:30
> > `daddylive_base = 'gfpMXf5BjIUoyx3oj8lQjG=='`
> 
> This is what my translations.py already had.

Odd, according to the code on here and what my copy had, "JjG==" so it had a J instead of Q. I suppose the old one might still work since I think it auto-forwards from the dlhd.sx to dlhd.so domain.

**Comment by vortex91** [comment] 2024-05-26 22:05
can  you guys merge to main branch and change version or do we need to wait for Rocky?

**Comment by rocky4546** [comment] 2024-05-27 03:16
PR does not work for me.

**Comment by rocky4546** [comment] 2024-05-27 03:27
PR works, but need updates.  I will wait and see if he makes the updates.

**Comment by rocky4546** [comment] 2024-05-27 13:39
Thank you @benjaminfrombe PR has been merged and validated.  You will need to refresh the channel list for DL.  Enjoy

**Comment by annjrue** [comment] 2024-05-27 14:02
I've been struggling with this for the past few days, just happened to check in when you fixed i, and I had to make an account to comment. This worked! Thank you!

**Closed** 2024-05-28 04:46 UTC
Labels: enhancement
